version: '3.2'
services:
  resource:
    # image: semtech/mu-cl-resources:1.17.1
    image: semtech/mu-cl-resources:latest
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    ports:
      - "500:80"

  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
